<script setup>
import { UiCard } from '@/components/ui'
import { appConfig } from '@/config/app'
</script>

<template>
  <div class="space-y-6">
    <div>
      <h2 class="text-xl font-bold tracking-tight text-gray-900">Settings</h2>
      <p class="mt-1 text-[13px] text-gray-500">Manage your {{ appConfig.name }} preferences.</p>
    </div>

    <UiCard>
      <template #header>
        <h3 class="text-base font-semibold text-gray-900">General</h3>
        <p class="text-[13px] text-gray-500">Configure general application settings.</p>
      </template>
      <p class="text-sm text-muted-foreground">Settings content will be generated by the SaaS generator based on your project configuration.</p>
    </UiCard>
  </div>
</template>
