import {
  LayoutDashboard as DashboardIcon,
  Users as UsersIcon,
  Settings as SettingsIcon,
  LogOut as LogOutIcon,
  Menu as MenuIcon,
  X as CloseIcon,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  Search,
  Plus,
  MoreVertical,
  Inbox,
  Rocket,
  Bell,
  Pencil,
  Trash2,
  Home
} from 'lucide-vue-next'

export const icons = {
  DashboardIcon,
  UsersIcon,
  SettingsIcon,
  LogOutIcon,
  MenuIcon,
  CloseIcon,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  Search,
  Plus,
  MoreVertical,
  Inbox,
  RocketIcon: Rocket,
  BellIcon: Bell,
  PencilIcon: Pencil,
  TrashIcon: Trash2,
  HomeIcon: Home,
}
